name: "Upload Deployment"
description: "Creates a new deployment by uploading a bundle."
author: TheMrMilchmann
inputs:
  username:
    description: "The username to use to authenticate against the Central Publisher API."
    required: true
  password:
    description: "The password to use to authenticate against the Central Publisher API."
    required: true
  base-url:
    description: "The base URL of the Central Publisher API."
    required: false
    default: "https://central.sonatype.com/"
  bundle:
    description: "The path to the deployment bundle."
    required: true
  name:
    description: "An optional name for the deployment."
    required: false
  publishing-type:
    description: "Specifies whether the deployment should proceed automatically after validation succeeded. One of: 'user-managed', 'automatic'"
    required: true
  validation-timeout:
    description: "The time to wait for validation of the deployment before failing."
    required: false
    default: "600"
outputs:
  deployment-id:
    description: "The ID of the newly created deployment."
runs:
  using: node20
  main: "../dist/upload-deployment/index.js"
branding:
  icon: upload
  color: orange
