name: "Drop Deployment"
description: "Drops a deployment."
author: TheMrMilchmann
inputs:
  username:
    description: "The username to use to authenticate against the Central Publisher API."
    required: true
  password:
    description: "The password to use to authenticate against the Central Publisher API."
    required: true
  base-url:
    description: "The base URL of the Central Publisher API."
    required: false
    default: "https://central.sonatype.com/"
  deployment-id:
    description: "The ID of the deployment to drop."
    required: true
runs:
  using: node24
  main: "../dist/drop-deployment/index.js"
branding:
  icon: delete
  color: orange
