name: CI
on:
  push:
    branches-ignore:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches-ignore:
      - 'v*'
    paths-ignore:
      - '**.md'
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Yarn install
        run: yarn install --immutable

      - name: Yarn build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Yarn install
        run: yarn install --immutable

      - name: Yarn test
        run: yarn test
