name: CI
on:
  push:
    branches-ignore:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches-ignore:
      - 'v*'
    paths-ignore:
      - '**.md'
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Yarn install
        run: yarn install --immutable

      - name: Yarn build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Yarn install
        run: yarn install --immutable

      - name: Yarn test
        run: yarn test
